# Generated by Django 5.2.9 on 2025-12-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='again_minutes',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='deck',
            name='easy_days',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='deck',
            name='good_days',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='deck',
            name='hard_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='deck',
            name='schedule_mode',
            field=models.CharField(default='hybrid', max_length=10),
        ),
    ]
