# Generated by Django 5.2.9 on 2025-12-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deck_again_minutes_deck_easy_days_deck_good_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='easy_days',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='good_days',
        ),
        migrations.AddField(
            model_name='deck',
            name='again_unit',
            field=models.CharField(choices=[('min', 'Minutes'), ('hour', 'Hours'), ('day', 'Days'), ('week', 'Weeks')], default='min', max_length=10),
        ),
        migrations.AddField(
            model_name='deck',
            name='easy_minutes',
            field=models.PositiveIntegerField(default=4320),
        ),
        migrations.AddField(
            model_name='deck',
            name='easy_unit',
            field=models.CharField(choices=[('min', 'Minutes'), ('hour', 'Hours'), ('day', 'Days'), ('week', 'Weeks')], default='day', max_length=10),
        ),
        migrations.AddField(
            model_name='deck',
            name='good_minutes',
            field=models.PositiveIntegerField(default=1440),
        ),
        migrations.AddField(
            model_name='deck',
            name='good_unit',
            field=models.CharField(choices=[('min', 'Minutes'), ('hour', 'Hours'), ('day', 'Days'), ('week', 'Weeks')], default='day', max_length=10),
        ),
        migrations.AddField(
            model_name='deck',
            name='hard_unit',
            field=models.CharField(choices=[('min', 'Minutes'), ('hour', 'Hours'), ('day', 'Days'), ('week', 'Weeks')], default='min', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='avg_think_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='due_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='deck',
            name='again_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='deck',
            name='hard_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='deck',
            name='schedule_mode',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('fixed', 'Fixed')], default='hybrid', max_length=10),
        ),
    ]
